---
- name: Converge
  hosts: all
  become: true
  vars:
    - zint_version: 2.4.2
    - zint_source: "https://github.com/downloads/zint/zint/zint-{{ zint_version }}.tar.gz"
    - zint_source_checksum: 'sha256:76547faaba0bfbea43733ab324e498863ebf21fc9a2e5db93512739d661a2b3a'
  pre_tasks:

    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_facts['os_family'] == 'Debian'
    - name: make | install make
      become: true
      apt:
        pkg: make
        state: present
  roles:
    - role: ansible-role-zint
