---
- name: Converge
  hosts: all
  become: true
  pre_tasks:

    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_facts['os_family'] == 'Debian'
    - name: make | install make
      become: true
      apt:
        pkg: make
        state: present
  roles:
    - role: ansible-role-zint
